This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./iss-thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file iss-thesis.acn....done (568 entries accepted, 0 rejected).
Sorting entries.......done (5629 comparisons).
Generating output file iss-thesis.acr....done (337 lines written, 0 warnings).
Output written in iss-thesis.acr.
Transcript written in iss-thesis.alg.
